// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDuiLkR32WChGtFdsmxz-Ukvo-JCsq8j8',
    appId: '1:934958716559:web:73d335f637b546ce5042fa',
    messagingSenderId: '934958716559',
    projectId: 'mps-bikes',
    authDomain: 'mps-bikes.firebaseapp.com',
    storageBucket: 'mps-bikes.firebasestorage.app',
    measurementId: 'G-P2HSLG8G29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuAfvm2v7IZi18apCfU4qC1oqbAJIjqj0',
    appId: '1:934958716559:android:19212f0d1fb664575042fa',
    messagingSenderId: '934958716559',
    projectId: 'mps-bikes',
    storageBucket: 'mps-bikes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS9Z6x8kRZMgqahkmDCCwWG1pyaKk-LME',
    appId: '1:934958716559:ios:641170a0170202a05042fa',
    messagingSenderId: '934958716559',
    projectId: 'mps-bikes',
    storageBucket: 'mps-bikes.firebasestorage.app',
    iosBundleId: 'dev.sayrix.financial.mpsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDuiLkR32WChGtFdsmxz-Ukvo-JCsq8j8',
    appId: '1:934958716559:web:9be92f084a1a78a85042fa',
    messagingSenderId: '934958716559',
    projectId: 'mps-bikes',
    authDomain: 'mps-bikes.firebaseapp.com',
    storageBucket: 'mps-bikes.firebasestorage.app',
    measurementId: 'G-DB7R8Y40SJ',
  );

}